# Generated by Django 4.0.5 on 2022-12-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=50, null=True, verbose_name='图片'),
        ),
    ]
