# Generated by Django 4.0.5 on 2022-12-21 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_images_project_image'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(default=0, verbose_name='用例ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('extract', models.CharField(max_length=200, verbose_name='提取规则')),
                ('value', models.CharField(default='', max_length=200, null=True, verbose_name='提取值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.TextField(verbose_name='URL')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('header', models.TextField(default='{}', null=True, verbose_name='请求头')),
                ('params_type', models.CharField(max_length=10, verbose_name='参数类型')),
                ('params_body', models.TextField(default='{}', null=True, verbose_name='参数内容')),
                ('response', models.TextField(default='{}', null=True, verbose_name='响应')),
                ('assert_type', models.CharField(max_length=10, null=True, verbose_name='断言类型')),
                ('assert_text', models.TextField(default='{}', null=True, verbose_name='断言结果')),
                ('is_delete', models.BooleanField(default=False, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.module')),
            ],
        ),
    ]
