# Generated by Django 4.0.5 on 2022-12-21 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('cases', '0002_testextract_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
